version: '2'
services:
    dotsub-app:
        image: dotsub
        external_links:
            - dotsub-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/dotsub
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dotsub-postgresql:
        extends:
            file: postgresql.yml
            service: dotsub-postgresql
